### ISSUE TITLE
Flow chart label text is truncated for some objects

### ISSUE THREAD

**Issue by terrywbrady** [mermaid-js/mermaid-cli#114]
Thank you for the great work on Mermaid.  This is a great tool.

**Describe the bug**
Here is the code for my diagram saved as `overview-core.mmd`.
```
%%{init: {'theme': 'base'}}%%
graph TD
  RDS[(Inventory DB)]
  UI("Merritt UI")
  ING(Ingest)
  ST(Storage)
  INV(Inventory)
  CLOUD(("Cloud Storage"))
  LDAP[/LDAP\]
  ZOO>Zookeeper]
  EZID(EZID Service)

  RDS --> UI
  UI --> |"file or manifest"| ING
  UI --> |authorization| LDAP
  ING --> |"async deposit"| ST
  ING --> ZOO
  ZOO --> ING
  ZOO --> INV
  UI ---> |download req| ST
  INV --> RDS
  ST --> CLOUD
  CLOUD -.-> |presigned| UI
  ING --> EZID

  style CLOUD fill:#77913C
  style RDS fill:#F68D2F
  style LDAP fill:cyan
  style ZOO fill:cyan
  style EZID fill:cyan
  
```

**To Reproduce**

I am using the following command to generate as svg file.

```
docker run --rm -v "$(pwd)/diagrams:/data" minlag/mermaid-cli mmdc -w 1200 -i overview-core.mmd
```

**Expected behavior**
The results are really nice, but a few text labels are truncated in the svg.  Look for the 4 red circles below.

**Screenshots**

<img width="723" alt="chartrunc" src="https://user-images.githubusercontent.com/1111057/114891573-d94e4880-9dc0-11eb-99b4-059a9bc7d6c3.png">

**Notes**
As a work around, I attempted to use BR tags, but I encountered #79 .

**Comment by MindaugasLaganeckas** [comment]
The error is visible only in SVG format. Both PNG and PDF work fine. Mermaid Live Editor produces an SVG file without problems listed in the issue.

**Comment by justsh** [comment]
I think I ran into the same issue this week, which seems to happen because of mermaid's default font list `{font-family: "trebuchet ms", verdana, arial, sans-serif;}`.
Trebuchet MS does not exist in the container but does exist on my OS, so the SVG geometry is calculated in the container with Arial (via Liberation Sans) but renders on my OS using Trebuchet MS which is too large.

I worked around this by setting the mermaid font in the mermaid CLI configFile explicitly, but a less surprising default might be to install the microsoft fonts contrib package into the mermaid CLI container image.

**Comment by MindaugasLaganeckas** [comment]
@justsh contributions are welcome 😄

**Comment by terrywbrady** [comment]
I just upgraded my script to use minlag/mermaid-cli:latest and the text sizing issue seems to be resolved.  I was most recently using minlag/mermaid-cli:8.13.3.

**Comment by MindaugasLaganeckas** [comment]
@terrywbrady : in this case, I will close the case. You are welcome to reopen it, if you disagree. Thank you for getting back with your comment😄
