### ISSUE TITLE
Add brew installation

### ISSUE THREAD

**Issue by vaxXxa** [mermaid-js/mermaid-cli#25]
**Is your feature request related to a problem? Please describe.**
I want to install `mermaid-cli` on my MacOS.

**Describe the solution you'd like**
Please add brew formula, that help mac-users to easy install `mermaid-cli`.

**Comment by MindaugasLaganeckas** [comment]
@vaxXxa : please, follow the template for the feature requests.

**Comment by vaxXxa** [comment]
> @vaxXxa : please, follow the template for the feature requests.

fixed

**Comment by MindaugasLaganeckas** [comment]
@vaxXxa  Would you consider making a PR? I will gladly review, if that formula works with linux. We are preparing for the release 8.6.1, that will come out soon. If done in time, the feature you are asking for would be released as well 😀

**Comment by BastianZim** [comment]
Hi @MindaugasLaganeckas,

I'd like to work on this but since this is, unfortunately, my first time working with non-python packages, I would have a short question if you don't mind.

Brew generally [prefers](https://docs.brew.sh/Node-for-Formula-Authors#download-url) an npm registry URL (With the format `https://registry.npmjs.org/<name>/-/<name>-<version>.tgz`) to a GitHub URL but I have no idea where to find that?
I found [this](https://www.npmjs.com/package/@mermaid-js/mermaid-cli) on the npm website but don't know where to find the URL.

Would you mind pointing out if such an URL exists and where I could find it?

Thanks!

**Comment by BastianZim** [comment]
See https://github.com/Homebrew/homebrew-core/pull/65521
