### ISSUE TITLE
STDIN Piping example is not working.

### ISSUE THREAD

**Issue by louis1001** [mermaid-js/mermaid-cli#271]
**Describe the bug**
I copied the example from the README, and it shows an error saying that you need an input file.
It's not recognizing the input from stdin.

**To Reproduce**

1. Install the cli
2. The path to the executable should be `<project root>/node_modules/.bin/mermaid`
3. Execute the example command from the README:
```bash
cat << EOF  | ./node_modules/.bin/mermaid
    graph TD
    A[Client] --> B[Load Balancer]
EOF
```

**Expected behavior**
According to the documentation, it should generate a graph and output it to STDOUT.

**What happens**
```
You had errors in your syntax. Use --help for further information.
You must specify at least one source file.
```

**Desktop (please complete the following information):**

- OS: macOS 12.3
- Arch: arm64 (Macbook M1)

**Additional context**
I plan to use this from node itself, with `child_process.exec`

**Comment by aloisklink** [comment]
Hi @louis1001, I don't recognise this error message. Additionally, the binary is not called `mermaid`, instead it is called `mmdc`. For me, the following works:

```bash
cat << EOF  | ./node_modules/.bin/mmdc   
    graph TD
    A[Client] --> B[Load Balancer]
EOF
```

I think you are using a different library. `mermaid-cli` should be installed with `npm install @mermaid-js/mermaid-cli`, and should be run with `./node_modules/.bin/mmdc`.

By the way, if you're planning on using this from node itself, my library [remark-mermaid-dataurl](https://github.com/aloisklink/remark-mermaid-dataurl) does this too. It's got a MIT license, so you're welcome to adapt/copy the function here: https://github.com/aloisklink/remark-mermaid-dataurl/blob/b191543fd73f82a1cb06da133823095e5fac49a8/index.js#L18-L131

It's a bit complicated though, mainly because we added a hook to mmdc to use a virtual file system so we don't need to write anything to the file system (some build systems like Docker/Vercel don't like writing to the file system, even in a `/tmp` directory)

**Comment by MindaugasLaganeckas** [comment]
I will close the issue based on the comment above.
