### ISSUE TITLE
How to setup up mermaid to use already installed chromium? 

### ISSUE THREAD

**Issue by habdank** [mermaid-js/mermaid-cli#331]
Hi!

We have installed by corporate platform Chromium based browser.
Due to security policies, no other browser is allowed.

Therefore starting mermaid-cli I am getting the following error:
```
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:553:9)
    at BrowserRunner.start (C:\Data\Tools\mermaid\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:116:34)
    at ChromeLauncher.launch (C:\Data\Tools\mermaid\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:117:16)
```

Is it possible to configure mermaid-cli to use other (pre-installed) chromium?

Thanks in advance for help.

**Comment by aloisklink** [comment]
Yes, it should be possible on Linux/MacOS, although I've got no idea if it will work on Windows.

If you run mermaid-cli with the `--help` flag, there's an option for `--puppeteerConfigFile`, which is a JSON configuration file for puppeteer.

These are options passed to [`puppeteer.launch`](https://pptr.dev/api/puppeteer.puppeteernode.launch/).

The useful options for you are:
  - [`executablePath`](https://pptr.dev/api/puppeteer.launchoptions.executablepath) Path to a browser executable to use instead of the bundled Chromium. Note that Puppeteer is only guaranteed to work with the bundled Chromium, so use this setting at your own risk. You may find https://github.com/puppeteer/puppeteer/blob/main/versions.js useful to see **which versions of Chrome are compatible with versions of puppeteer**.
  - [`product`](https://pptr.dev/api/puppeteer.product) (in case you want to use firefox instead of chrome)
  - [`timeout`](https://pptr.dev/api/puppeteer.launchoptions.timeout) can be used to increase/decrease timeout before puppeteer throws an error

You'll probably want a file called `puppeteerConfigFile.json` with contents:

```json
{
  "executablePath": "C:\\path\\to\\your\\chrome.exe"
}
```

Then run mermaid-cli with option `mmdc --puppeteerConfigFile puppeteerConfigFile.json`.

You might also be able to do the same thing with environment variables by following: https://pptr.dev/#environment-variables.

**Comment by MindaugasLaganeckas** [comment]
@habdank : if you can confirm the solution above, then we will create a section in  our docs for it.

**Comment by shntnu** [comment]
> You might also be able to do the same thing with environment variables by following: https://pptr.dev/#environment-variables.

Confirmed

```
export PUPPETEER_EXECUTABLE_PATH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

works on

```
❯ uname -a
Darwin wm89a-c9c 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:55 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6031 arm64 arm Darwin
```
