### ISSUE TITLE
Does not render a particular diagram.

### ISSUE THREAD

**Issue by sidharthv96** [mermaid-js/mermaid-cli#432]
**Describe the bug**
<img width="587" alt="image" src="https://user-images.githubusercontent.com/10703445/203308219-362fb4b1-1c3a-4310-95f3-1eec78d5a217.png">

**To Reproduce**
- Visit https://text-to-diagram.com/?b=mermaid&example=wiiu

**Expected behavior**
Renders the image

PS: I didn't test in the CLI, just shared this when I saw it in the site.

**Comment by MindaugasLaganeckas** [comment]
Thank you for reporting it! :)

**Comment by MindaugasLaganeckas** [comment]
I do not see which nodejs version was used to create a diagram. We support >= 14.1 nodejs.

**Comment by aloisklink** [comment]
It works fine for me when using the current `@mermaid-js/mermaid-cli` master branch.

![wii-arch](https://user-images.githubusercontent.com/19716675/203665244-d9fc1588-fdc7-463e-8333-8f09daf12dbb.svg)

Maybe the website is using https://www.npmjs.com/package/mermaid.cli instead of https://www.npmjs.com/package/@mermaid-js/mermaid-cli?

If anyone has access to that NPM package, maybe they can do an [npm deprecate](https://docs.npmjs.com/cli/v8/commands/npm-deprecate) on it, something like:

```bash
npm deprecate mermaid.cli "Development has moved to the '@mermaid-js/mermaid-cli' package"
```

Ideally we'd also close all the open issues/PRs in https://github.com/mermaidjs/mermaid.cli and [archive that repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) since it looks like there are still people reporting bugs there.

Maybe with a message that says:

> Development on this project has moved to https://github.com/mermaid-js/mermaid-cli
>
> If this issue/PR is still valid, please re-create this issue in the new repository and add a link to this issue/PR.

A script like https://gist.github.com/mauritsvanrees/f0dc7d829a1957a1771adbf0e86057c5 might help, but then again, there are only ~60 or so open issues/PRs, so it might be faster to manually close every issue.

**Comment by aloisklink** [comment]
Ah, I think I see the issue. `@mermaid-js/mermaid-cli@9.2.2` works (latest version), but `@mermaid-js/mermaid-cli@9.1.7` (latest version 7 days ago) doesn't work with that diagram.

I think the issue might have been that mermaid.live was already running Mermaid 9.2.x before mermaid-cli was updated.

**Comment by alixander** [comment]
yeah i was using 9.1.7, installed with brew. It looks like brew dist is discontinued now?

here's the cmd i ran to render: https://github.com/terrastruct/text-to-diagram-site/blob/master/ci/render.sh#L25

noted about documenting the versions, i'll be sure to include that.
