### ISSUE TITLE
[Docker] Use an absolute path for the entrypoint

### ISSUE THREAD

**Issue by daamien** [mermaid-js/mermaid-cli#435]
**Describe the bug**

When using the docker image, specifying `/data` twice is a bit confusing: 

```
docker run -it -v /path/to/diagrams:/data minlag/mermaid-cli -i /data/diagram.mmd
```

**Expected behavior**

The following syntax would be easier:

```
docker run -it -v `pwd`:/data minlag/mermaid-cli -i ./path/to/diagram.mmd
```

**Solution**

Define an absolute path for the entrypoint and set the workdir to `/data` 

```
ADD puppeteer-config.json  /puppeteer-config.json
WORKDIR /data
ENTRYPOINT ["/home/mermaidcli/node_modules/.bin/mmdc", "-p", "/puppeteer-config.json"]
```

**Comment by aloisklink** [comment]
> Define an absolute path for the entrypoint

This makes sense for me! PRs are welcome.

> set the workdir to `/data`

This might be a breaking change (e.g. if someone previously wrote `docker run -it -v $(pwd):/home/mermaidcli/data minlag/mermaid-cli -i ./data/diagram.mmd`)

It seems pretty rare that somebody would have done this, so there might only be a low risk of this breaking somebody's code.

Do you know if other Docker images also change the workdir to a folder that will be mounted? That would make the case for changing the `WORKDIR` much stronger.

**Comment by MindaugasLaganeckas** [comment]
Very good discussion. Docker image does not change workdir to the folder, that is mounted. 
How would it work with multiple mounts?
Yes, there is a risk to break someone's scripts, but after doing a search in github I am not so concerned.
As @aloisklink PRs are welcome 😄

**Comment by daamien** [comment]
> Do you know if other Docker images also change the workdir to a folder that will be mounted? 
> That would make the case for changing the `WORKDIR` much stronger.

The pandoc docker does it:
https://github.com/pandoc/dockerfiles/blob/master/ubuntu/Dockerfile#L167

and you launch it like this 

```
docker run  -v `pwd`:/data pandoc/latex foo.md
```

The point is to mount the current directory and use the docker image as binary command inside that directory

**Comment by daamien** [comment]
Thanks !

**Comment by aloisklink** [comment]
> The pandoc docker does it:
> https://github.com/pandoc/dockerfiles/blob/master/ubuntu/Dockerfile#L167
> 
> and you launch it like this 
> 
> ```
> docker run  -v `pwd`:/data pandoc/latex foo.md
> ```
> 
> The point is to mount the current directory and use the docker image as binary command inside that directory

In that case, I'm open to changing the `Dockerfile`'s default `WORKDIR`, especially since as @MindaugasLaganeckas said, there's a low chance of it breaking anything, and it definitely does make using the docker image easier! :smile:

**Comment by daamien** [comment]
As a follow up, if the change breaks something, it will be fairly easy to restore the current behaviour with the `--workdir` option

```
docker run [...] --workdir=/home/mermaidcli minlag/mermaid-cli  -i /data/diagram.mmd -o /data/diagram.svg
````

**Comment by daamien** [comment]
Hi @MindaugasLaganeckas !

Maybe I am missing something but the latest image on docker hub does not have the entrypoint.... 

https://hub.docker.com/layers/minlag/mermaid-cli/latest/images/sha256-7e6f3f7e5559e44c8266266d0c25b904716c8596fb69240ba71a288419af6e36?context=explore

The latest image is built with the Dockerfile of the master branch ?

**Comment by aloisklink** [comment]
Ah, I think I see what the issue is. The pre-releases (e.g. `v9.3.1-beta.1`) are created using the `DockerfileBuild` file, not the `Dockerfile`.

https://github.com/mermaid-js/mermaid-cli/blob/34691b3fa58d7884646fc5f085e4d98b1445a620/.github/workflows/compile-mermaid.yml#L10

Only the stable releases use the `Dockerfile` file: https://github.com/mermaid-js/mermaid-cli/blob/34691b3fa58d7884646fc5f085e4d98b1445a620/.github/workflows/release-publish.yml#L12 but for some reason the stable `v9.3.0` release also seems to be using a relative entry point: https://hub.docker.com/layers/minlag/mermaid-cli/9.3.0/images/sha256-d1543aa2ce14f04c7ef232f7b9b151b9ef22754d06c76d023ce4494ee9dbe141?context=explore

Maybe both CI actions are running at once and are conflicting?

@daamien, any chance you want to create a new PR for it changing https://github.com/mermaid-js/mermaid-cli/blob/master/DockerfileBuild ? I'll let you claim the credit for it :wink:
