### ISSUE TITLE
Titles Break Markdown Rendered In Sequence Diagrams

### ISSUE THREAD

**Issue by apeacock1991** [mermaid-js/mermaid-cli#452]
**Describe the bug**

When using the CLI to convert diagrams in Markdown to SVGs, it breaks if the diagram includes a title. The diagram itself (the SVG) seems fine, but the Markdown looks like this:

`![diagram](./path-to-svg.svg "TheTitle")`

For some reason, the title ends up in the path to the SVG, breaking the page.

**To Reproduce**

1. Create a sequence diagram with a title
2. Include it in a Markdown file
3. Run the CLI command to convert Mermaid in Markdown
4. You'll see the link is broken

**Expected behavior**

**Comment by aloisklink** [comment]
Adding titles to images is part of the original Markdown spec, and so should work on every Markdown program: https://daringfireball.net/projects/markdown/syntax#img

Which markdown program are you using?

My gut feeling is that this may be a bug in your Markdown program, but it's probably worth testing the Markdown in other programs, since there is a chance that something is wrong with escaping the title.

**Comment by apeacock1991** [comment]
> Adding titles to images is part of the original Markdown spec, and so should work on every Markdown program: https://daringfireball.net/projects/markdown/syntax#img
> 
> Which markdown program are you using?
> 
> My gut feeling is that this may be a bug in your Markdown program, but it's probably worth testing the Markdown in other programs, since there is a chance that something is wrong with escaping the title.

It's just a regular Markdown file, I'm not using any program, I am running the Mermaid CLI on the Markdown file. It's worth noting it's fine for all diagram types _except_ sequence diagram, so I think it's something particular with that, but no idea what!
