### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by konstantinblaesi** [mermaid-js/mermaid-cli#486]
What package do I install to get TypeScript types or is there no such package or types ?

**Comment by aloisklink** [comment]
There's currently no such types, unfortunately.

It should be pretty easy to add, however, since most of our functions already have JSDoc to declare the types of the functions.

I've got a proof-of-concept at https://github.com/aloisklink/mermaid-cli/tree/feat/add-typescript, but there's a few TypeScript errors that I don't want to fix now, as they'd cause merge conflicts with the currently open PRs.
