### ISSUE TITLE
File generation not happening

### ISSUE THREAD

**Issue by jaques-sam** [mermaid-js/mermaid-cli#552]
**Description**
mmdc doesn't generate a file nor outputs any error.
I tried all 3 supported output types.
I tried also inside the directory itself.
I did an `npm uninstall mmdc` + `npm install mmdc`
None of them worked.

**How to reproduce**
```
❯ cat doc/assets/virtual_microphone.mmd              
---
title: Virtual microphone
---

graph LR
    A[AES6 Dante IN] --> B[AES67-daemon] --> C[ALSA Sink]

❯ mmdc -i doc/assets/virtual_microphone.mmd -o vm.png

❯ ls doc/assets/vm.png

❯ ls vm.png           
ls: cannot access 'vm.png': No such file or directory

❯ mmdc -V                                            
0.5.1
```

**Expected behavior**
I expect the png/pdf/svg file being generated. 

**Desktop**
- OS: Fedora 28
- mmdc version: 0.5.1

**Comment by aloisklink** [comment]
Hmmmm, that's weird. I actually own the `mmdc` package, but the only thing it does is install `@mermaid-js/mermaid-cli`, see https://www.npmjs.com/package/mmdc.

Because of that, it should be completely compatible with `npm install -g @mermaid-js/mermaid-cli`.

(it's mainly there to prevent someone else from stealing the `mmdc` package and sticking some malicious code there, like the [`tsc`](https://www.npmjs.com/package/tsc) package)

IMO, in case you're curious, there's some discussion about possibly changing the name of this package in https://github.com/mermaid-js/mermaid-cli/issues/433!
