### ISSUE TITLE
Client does not start

### ISSUE THREAD

**Issue by tensionhead** [mermaid-js/mermaid-cli#572]
**Describe the bug**
After global (or local) installation with npm, hitting `mmdc` in the terminal gives:
```bash
file:///usr/local/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:260
      const svg = container.getElementsByTagName?.('svg')?.[0]
                                                 ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
```

**To Reproduce**

1. Install the mermaid client via `npm install -g @mermaid-js/mermaid-cli` 
2. run the `mmdc` client in a terminal

**Desktop :**

OS: Ubuntu 22.04

**Additional context**
I also tried the alternative installation instructions, a local installation via npm yields the exact same error. Installation via `yarn` failed because of dependecy issues.

**Comment by KSR-Yasuda** [comment]
Perhaps are you using Node.js < 14.x ?
[Optional chaining (`?.`) syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is supported from Node v14.

**Comment by tensionhead** [comment]
Indeed, the standard Node.js installation from the Ubuntu software sources gives version `v12.x`. Thanks, I am gonna check how to install a >= `v14.x` version!

**Comment by tensionhead** [comment]
Ok I think I got it, using
```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
```
then `nvm install --lts`  and finally `npm install @mermaid-js/mermaid-cli` I got the client running! Node.js is now `v18.17.0` and `mmdc` works :rocket:

**Comment by aloisklink** [comment]
Yep, sorry, we only support Node v14.13 and up, and we'll soon have to drop Node v14 support, since it's no longer supported by the Node.JS team, and many of our dependencies are dropping support too.

It's listed in https://github.com/mermaid-js/mermaid-cli/blob/57f826263e52c7ff821372c1c3f3a811c36ff7bf/package.json#L13, so NPM should have printed a warning about it, but your NPM version might have been too old for this!

> Node.js installation from the Ubuntu software sources

FYI, I would highly recommend not using the default Ubuntu apt repo for Node.JS. LTS Node.JS releases are only actively maintained by the Node.JS team for 2.5 years (see https://github.com/nodejs/release#release-schedule). Afterwards, you're relying on the Debian/Ubuntu team to fix security issues, but they generally struggle with backporting security fixes, since Node.JS is a very large project.

NVM is great if you're a developer, but since it's doesn't automatically update Node.JS, it's not great from a security standpoint.

If you're running Ubuntu, [`snap`](https://snapcraft.io/node) or the [NodeSource `apt` repo](https://github.com/nodesource/distributions#installation-instructions) are generally what I'd recommend using to install Node.JS, so that you'll get automatic updates!
