### ISSUE TITLE
Does the version of project mermaid-cli correspond to that of mermaid ?

### ISSUE THREAD

**Issue by SealinGp** [mermaid-js/mermaid-cli#601]
## Help us help you!

my target:
i just want mermaid-cli can use [mermaid](https://github.com/mermaid-js/mermaid) v10.4.0

one ways to use mermaid v10.4.0 i can think of 
1. i clone this project and change package.json mermaid to 10.4.0 localy and use it 
```
npm i
node src/cli.js
```

Is there other ways ?

**Comment by aloisklink** [comment]
Hi, the pre-built of `mermaid-cli` published to NPM at https://www.npmjs.com/package/@mermaid-js/mermaid-cli (e.g. if you do `npm install @mermaid-js/mermaid-cli`) do follow Mermaid's versioning, at least for the MAJOR and MINOR versions. E.g. v10.4.x of the mermaid-cli project will match with v10.4.y of the mermaid project.

We do have a [message in the README.md about this](https://github.com/mermaid-js/mermaid-cli/blob/d236fc2e1d393a3f134f2e8ef9f4c55e0d3bc96a/README.md?plain=1#L174-L175), but maybe it could be made more clear? We'd love to hear suggestions!

If you clone this project locally and use `yarn install`, it will pick v10.4.0 for you, since that's the version in our `yarn.lock` file:

https://github.com/mermaid-js/mermaid-cli/blob/d236fc2e1d393a3f134f2e8ef9f4c55e0d3bc96a/yarn.lock#L3992-L3993

We currently rely on @dependabot to automatically update this file for us, but we could probably set it to automatically update the `package.json` file at the same time, using the [`versioning-strategy` `increase` option](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy).
