### ISSUE TITLE
Discontinue Node 14 and Node 16 support for mermaid-cli

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [mermaid-js/mermaid-cli#618]
Let's plan and discontinue Node 14 and Node 16 support for mermaid-cli.
Why?
We cannot updated some of our dependencies to the latest versions due to the restriction above. We loose the newest security and performance enhancements.
The primary usecase of the mermaid-cli is to be used as a command line tool (not a shared library).
@aloisklink do you have any inputs/objections? If not we could plan to implement the breaking change 2024 Q2 (just a suggestion).

**Comment by aloisklink** [comment]
I don't want to make any breaking changes without making a v11 release, since it's probably even more difficult for command-line users to know that they need to update their Node.JS version, since they don't have experience with the Node.JS eco-system.

I believe the "mermaid" project is planning on making a v11 release before Christmas/New Year's, so we should hopefully be able to drop Node v14/Node v16 support then too.

Then, [Node v18 will be supported until 2025-04-30](https://github.com/nodejs/Release), so we won't have to worry about this for another 2 years. However, we could even drop Node v18 support now too, since that way we should always be ahead of our dependencies.

The only dependency I'm worried about not updating is puppeteer, although the newer versions are actually slower than the current version :laughing:

**Comment by MindaugasLaganeckas** [comment]
As usual super high quality input @aloisklink 😄 Do you suggest to move to Node v20 starting from mermaid v11 release? Meaning, Node v14, Node v16, Node v18 will be dropped starting from mermaid v11. If yes, then I will update the README in mermaid-cli and will post a message in Slack.

**Comment by MindaugasLaganeckas** [comment]
Ok. Rogger that :) We will drop Node v14 and v16 only with mermaid v11 release. Thank you for your inputs. :)
