### ISSUE TITLE
Upgrade puppeteer

### ISSUE THREAD

**Issue by astrojuanlu** [mermaid-js/mermaid-cli#627]
**Is your feature request related to a problem? Please describe.**
I'd like to use Puppeteer with Firefox https://hacks.mozilla.org/2023/12/puppeteer-webdriver-bidi/ which requires 21.6.0.

The version currently pinned, `^19.0.0`, is no longer supported:

```
$ PUPPETEER_PRODUCT=firefox npm install -g @mermaid-js/mermaid-cli 
npm WARN deprecated puppeteer@19.11.1: < 21.3.7 is no longer supported
...
```

**Describe the solution you'd like**
mermaid-cli upgrades to a compatible Puppeteer version.

**Describe alternatives you've considered**
-

**Additional context**
I want this for pragmatic reasons but also I want to stop using Chrom{e,ium} everywhere 😉

**Comment by aloisklink** [comment]
We haven't yet upgraded Puppeteer because we're on the latest version that still supports Node.JS v14 and v16, but we're planning on dropping support for these older Node.JS versions in the next major v11 release, see https://github.com/mermaid-js/mermaid-cli/issues/618

As a temporary fix, and if you don't mind dropping Node.JS v14/v16 support, you can use your package manager's override feature, e.g. for NPM, you can add the following to your [`package.json`'s `overrides` field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides):

```json
{
  "overrides": {
    "@mermaid-js/mermaid-cli@^10.6.1": {
      "puppeteer": "^21"
    }
  }
}
```
