### ISSUE TITLE
Upgrade mermaid to 10.9.0 (Latex support)

### ISSUE THREAD

**Issue by maikol-solis** [mermaid-js/mermaid-cli#680]
**Describe the bug**

The new latest mermaid 10.9.0 has Latex support. mermaid-cli is still in version 10.8.0. 

Merging the PR #663 will do it.  

Best.

**Comment by MindaugasLaganeckas** [comment]
Switch to 10.9.0 is blocked by broken regression suite.

**Comment by aloisklink** [comment]
Mermaid v10.9.0 greatly increases the size of the bundle, and that seems to be causing issues with tests.

I'm looking into a way of fixing it but my gut feeling is that it might be a bit of work, since we might need to dig into Puppeteer internals to support splitting up the bundle into multiple parts, without triggering CSP/CORs errors.

This comment https://github.com/puppeteer/puppeteer/issues/1229#issuecomment-1013831359 looks promising!

Unfortunately, I haven't really had the free time to look at for the past few weeks, since I've been ill, but I'll see if I can get a chance to look at in the next few days! Otherwise, help would be appreciated!
